[package]
name = "cc-test"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[lib]
name = "cc_test"
doctest = false
test = false

[build-dependencies]
cc = { path = ".." }

[features]
parallel = ["cc/parallel"]
